
export const SHARJAH_DISTRICTS: string[] = [
  'Al Ghafia',
  'Al Goaz',
  'Al Gharayen',
  'Al Juraina',
  'Al Helio',
  'Al Hamriyah',
  'Al Hazannah',
  'Al Khan',
  'Al Khaledia',
  'Al Layyeh',
  'Al Majaz',
  'Al Manakh',
  'Al Mareija',
  'Al Mirgab',
  'Al Muntazah',
  'Al Nabba',
  'Al Nahda',
  'Al Nasserya',
  'Al Qadisiya',
  'Al Qasimia',
  'Al Rahmaniya',
  'Al Ramla',
  'Al Rifa a',
  'Al Riqa',
  'Al Sabkha',
  'Al Segaya',
  'Al Shahba',
  'Al Sharq',
  'Al Soor',
  'Al Tala a',
  'Al Yarmook',
  'Barashi',
  'Bu Tina',
  'Dasman',
  'Halwan',
  'Maysaloon',
  'Muwafjah',
  'Muwailih',
  'Nekhailat',
  'Rolla Area',
  'Samnan',
  'Sharqan',
  'Umm Khanoor',
];
